version: '3'
services:
  nginx:
    image: "nginx:latest"
    restart: unless-stopped
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Auth
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=pandey909
    volumes:
      - auth-mysql-datavolume:/var/lib/mysql
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
volumes:
  auth-mysql-datavolume: