version: '3'
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Auth_testing
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=pandey909
    volumes:
      - auth-testing-mysql-datavolume:/var/lib/mysql
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run ci
    volumes:
      - .:/app
    depends_on:
      - mysql
volumes:
  auth-testing-mysql-datavolume: