version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Auth
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=pandey909
    volumes:
      - auth-mysql-datavolume:/var/lib/mysql
  app:
    build:
      dockerfile: Dockerfile
      context: .
    # ports:
    #   - "4000:4000"
    volumes:
      - .:/app
volumes:
  auth-mysql-datavolume: